repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
    -   id: check-case-conflict
    -   id: end-of-file-fixer
-   repo: https://github.com/IamTheFij/docker-pre-commit
    rev: v2.1.0
    hooks:
    -   id: hadolint
-   repo: https://github.com/markdownlint/markdownlint
    rev: 6033ecf03c71767b6625cb97d5f51a247b0d611e
    hooks:
    -   id: markdownlint_docker
